# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-23 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0002_auto_20161020_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resolutions',
            new_name='Resolution',
        ),
    ]
