# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0003_auto_20161023_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='cookie',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
